FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y build-essential \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "ui/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
